### PR TITLE
Styled add item page and list view

### PR DESCRIPTION
**Pull request by ashill99**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._ 

## Description

Edited the Add item page and the List page to fit the theme and given it a more modern style and feel. 

## Acceptance Criteria

Listview: 

Add outline to the surrounding list, to stay uniform with add item page
Update colors on background items (or make borders around items), be mindful of font color on background
Round edges, increase size of each list item
Update checkbox

Add Item: 

Update buttons and input fields to match styling of rest of site
Position items in center of page
Put title in the header
Add border radius and shadowing to input box

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Updates

Screen Shot 2021-05-29 at 9 40 28 PM

Screen Shot 2021-05-29 at 9 40 53 PM

## Testing Steps / QA Criteria

Take a look and let me know your thoughts.

### CODE REVIEW

**Review by vanmars — APPROVED** [review]
Wow, nice work! Especially love the colored border on items!

**Comment by lyleschemmerling** [comment]
lgtm

**Comment by tarynblakemiller** [comment]
Nice Adam!!

**Review by lyleschemmerling — CHANGES_REQUESTED** [review]
I don't think the package lock should have changes here

**Review by CodenameTam — APPROVED** [review]
This looks amazing🥰

**Pull request merged**
